export const experiencesEn = [
  {
    title: 'Angular web developer',
    company: 'Cyber Ensenble Outsourcing Services Inc., CDO, Ph',
    period: '2022 - 2025 (3 years)',
    technologies: 'Angular, Angular Material, Typescript',
    missions: [
      'Replicated a site from non-Angular to Angular.',
      'Maintained the site for optimal performance.',
      'Added new features and resolved tickets.',
      'Focused on frontend development and API integration.',
      'Customized user interfaces.',
      'Participated in weekly progress meetings.',
      'Led code flow and overall implementation of the site.',
    ],
    detailIsDisplayed: false,
  },
  {
    title: 'Laravel web developer',
    company: 'Embernxt, CDO, Ph',
    period: '2024 - 2025 (1 Year)',
    technologies: 'Laravel, PHP, Javascript',
    missions: [
      'Integrated APIs into templates.',
      'Modified UI and fixed bugs.',
      'Implemented payment methods using PayMaya.',
      'Collaborated with teammates.',
      'Participated in weekly progress meetings.',
    ],
    detailIsDisplayed: false,
  },
  {
    title: 'Wordpress web developer',
    company: 'Apply flow, Remote, Australia',
    period: '2023 - 2024 (1 year)',
    technologies: 'Wordpress, Figma, Beaver Builder, Elementor',
    missions: [
      'Replicated site based on Figma design using WordPress.',
      'Created customizable web pages using JavaScript and SCSS.',
      'Developed sites with animation features based on client needs.',
      'Remotely monitored progress using Hubstaff.',
      'Submitted daily progress reports.',
    ],
    detailIsDisplayed: false,
  },
  {
    title: 'Freelance developer',
    company: 'Self Employment, CDO, Ph',
    period: '2022 - 2023 (1 year)',
    technologies:
      'Flutter, Dart, Angular, Html, Javascript, Typescript, Scss, Firebase',
    missions: [
      'Collected and analyzed client requirements to ensure project objectives were clearly defined and achievable.',
      'Developed web and/or mobile applications based on client needs.',
      'Conducted weekly meetings to provide project updates.',
      'Gained hands-on experience in handling clients directly.',
      'Enhanced technical knowledge to better support client requirements.',
    ],
    detailIsDisplayed: false,
  },
  {
    title: 'Mobile App Developer, CDO, Ph',
    company: 'Eihap (Defunct startup)',
    period: '2020 (10 months)',
    technologies: 'Flutter, Dart',
    missions: [
      'Built application features.',
      'Assisted senior developers.',
      'Debugged, refactored, and fixed application features.',
      'Gained deeper knowledge in programming fundamentals and hands-on work experience.',
    ],
    detailIsDisplayed: false,
  },
];
